version: '3.9'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NGINX_CONFIG: frontend.conf
    env_file:
      - ./common.env
    ports:
      - 80:80